import Head from "next/head";
import {useEffect, useState} from "react";
import {getUsers} from "~/server/actions/user";


export default function Home() {
    const [users, setUsers] = useState([])
    useEffect(() => {
        getUsers()
            .then((data) => {
            setUsers(data)
        })
    } ,[])

  return (
    <>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
           testing purposes
          </h1>
            <h2 className="text-2xl font-bold text-white">Users</h2>
            <ul>
                {users?.map((user) => (
                    <li key={user.id}>{user.name}</li>
                ))}
            </ul>
        </div>
      </main>
    </>
  );
}
