import Head from "next/head";
import Hero from "../components/Hero";
export default function Home() {

  return (
    <>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
          <nav className={"min-h-4 border-b-2 border-e-black"}></nav>
          <Hero></Hero>
      </main>
    </>
  );
}
